const USERS_REQUESTED = 'all/USERS_REQUESTED';
const USERS_RECEIVED = 'all/USERS_RECEIVED';
const USERS_ERROR = 'all/USERS_ERROR';

const USERS_COUNT_REQUESTED = 'users/COUNT_REQUESTED';
const USERS_COUNT_RECEIVED = 'users/USERS_COUNT_RECEIVED';
const USERS_COUNT_ERROR = 'users/USERS_COUNT_ERROR';

const SOME_USERS_REQUESTED = 'few/SOME_USERS_REQUESTED';
const SOME_USERS_RECEIVED = 'few/SOME_USERS_RECEIVED';
const SOME_USERS_ERROR = 'few/SOME_USERS_ERROR';


const USER_DETAILS_REQUESTED = 'one/USER_DETAILS_REQUESTED';
const USER_DETAILS_RECEIVED = 'one/USER_DETAILS_RECEIVED';
const USER_DETAILS_ERROR = 'one/USER_DETAILS_ERROR';

const TOP_USERS_REQUESTED = 'top/TOP_USERS_REQUESTED';
const TOP_USERS_RECEIVED = 'top/TOP_USERS_RECEIVED';
const TOP_USERS_ERROR = 'top/TOP_USERS_ERROR';

 

	 

const Actions = {
    USERS_REQUESTED,
    USERS_RECEIVED,
    USERS_ERROR,
    USERS_COUNT_REQUESTED,
    USERS_COUNT_RECEIVED,
    USERS_COUNT_ERROR,
    SOME_USERS_REQUESTED,
    SOME_USERS_RECEIVED,
    SOME_USERS_ERROR,
    USER_DETAILS_REQUESTED,
    USER_DETAILS_RECEIVED,
    USER_DETAILS_ERROR,
    TOP_USERS_REQUESTED,
    TOP_USERS_RECEIVED,
    TOP_USERS_ERROR


};

export default Actions;